---
- block:
  - name: Get Vector distrib
    ansible.builtin.get_url:
      url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
      dest: "./vector-{{ vector_version }}.rpm"
- name: install vector packages
  become: true
  ansible.builtin.yum:
    name:
      - vector-{{ vector_version }}.rpm
- name: Vector | Template config
  become: true
  ansible.builtin.template:
    src: "templates/vector.config.j2"
    dest: "{{ vector_config_dir }}/vector.yaml"
- name: Vector | Register service
  become: true
  ansible.builtin.template:
    src: "templates/vector.service.j2"
    dest: "/etc/systemd/system/vector.service"
